# Use the official Node.js 20 image with Alpine Linux
FROM node:22.11.0-alpine AS base

# Set the working directory inside the container
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
  else echo "Lockfile not found." && exit 1; \
  fi

# Copy the rest of the application code
COPY . .

# Expose the port that Next.js runs on
EXPOSE 3000

# Create a start.sh script to run the development server
RUN echo '#!/bin/sh\n\
if [ -f yarn.lock ]; then yarn dev; \
elif [ -f package-lock.json ]; then npm run dev; \
elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm dev; \
else echo "Lockfile not found." && exit 1; \
fi' > /app/start.sh && chmod +x /app/start.sh

# Set the default command to run start.sh
CMD ["sh", "/app/start.sh"]
